export interface EmployeeProfile {
  id: number,
  employeeNumber: string,
  taxNumber: string,
  engagementDate: Date,
  terminationDate: Date,
  reportingLine: number,
  highestQualification: string,
  disability: boolean,
  disabilityNotes: string,
  countryOfBirth: string,
  nationality: string,
  level: number,
  employeeType: {
    id: number,
    employeeNumber: string,
    taxNumber: string,
    engagementDate: Date,
    terminationDate: Date | null,
    reportingLine: number,
    highestQualification: string,
    disability: boolean,
    disabilityNotes: string,
    countryOfBirth: string,
    nationality: string,
    level: number,
    employeeType: {
      id: number,
      name: string,
    },
    title: string,
    name: string,
  },
  title: string,
  name: string,
  initials: string,
  surname: string,
  dateOfBirth: Date,
  idNumber: string,
  passportNumber: string,
  passportExpirationDate: Date,
  passportCountryIssue: string,
  race: number,
  gender: number,
  knownAs: string,
  pronouns: string,
  email: string,
  personalEmail: string,
  cellphoneNo: string,
  tshirtSize: number,
  photo : string
}
