
export interface EmployeeProfilePermissions {
  id: boolean,
  employeeNumber: boolean,
  taxNumber: boolean,
  engagementDate: boolean,
  terminationDate: boolean,
  peopleChampion: boolean,
  disability: boolean,
  disabilityNotes: boolean,
  countryOfBirth: boolean,
  nationality: boolean,
  level: boolean,
  employeeType: boolean,
  name: boolean,
  initials: boolean,
  surname: boolean,
  dateOfBirth: boolean,
  idNumber: boolean,
  passportNumber: boolean,
  passportExpirationDate: boolean,
  passportCountryIssue: boolean,
  race: boolean,
  gender: boolean,
  email: boolean,
  personalEmail: boolean,
  cellphoneNo: boolean,
  photo: boolean,
  notes: boolean,
  leaveInterval: boolean,
  salaryDays: boolean,
  payRate: boolean,
  salary: boolean,
  clientAllocated: boolean,
  teamLead: boolean,
  physicalAddress: boolean,
  postalAddress: boolean,
  houseNo: boolean,
  emergencyContactName: boolean,
  emergencyContactNo: boolean
  [key: string]: boolean;
}