trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Staging
  jobs:
  - job: BuildAndDeployStaging
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'staging_env'

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.TempDirectory)
        Contents: '**\staging_env'
        TargetFolder: $(Build.SourcesDirectory)

    - script: |
        mv $(Build.SourcesDirectory)/staging_env $(Build.SourcesDirectory)/.env
      displayName: 'set up .env file'

    - script: |
        npm install
        npm run build -- --configuration=staging
      displayName: 'npm install and build for staging'

    - task: CopyFiles@2
      inputs:
        contents: 'dist/**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/staging'
      displayName: 'Copy files to staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/staging'
        artifactName: 'staging-drop'
      displayName: 'Publish Artifact for Staging'

- stage: Production
  jobs:
  - job: BuildAndDeployProd
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'production_env'
        
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.TempDirectory)
        Contents: '**\production_env'
        TargetFolder: $(Build.SourcesDirectory)
        
    - script: |
        mv $(Build.SourcesDirectory)/production_env $(Build.SourcesDirectory)/.env
      displayName: 'set up .env file'

    - script: |
        npm install
        npm run build -- --configuration=production
      displayName: 'npm install and build for production'

    - task: CopyFiles@2
      inputs:
        contents: 'dist/**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/prod'
      displayName: 'Copy files to staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/prod'
        artifactName: 'prod-drop'
      displayName: 'Publish Artifact for Production'