export interface candidateDocument{
    id: number,
    name: string,
    surname: string,
    personalEmail: string,
    potentialLevel: number,
    jobPosition: number,
    linkedIn: string,
    profilePicture: string,
    cellphone: string,
    location: string,
    cv: string,
    portfolioLink: string,
    portfolioPdf: string,
    gender: number,
    race: number,
    idNumber: string,
    referral: number,
    highestQualification: string,
    school: string,
    fieldOfstudy: string,
    qualificationEndDate : Date
}