export const countries = [
    'South Africa',
    'India',
    'China',
    'Russia',
    'United Kingdom',
    'United States',
    'Australia',
    'New Zealand',
    'Germany',
    'France',
    'Spain',
    'Italy',
    'Netherlands',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Switzerland',
    'Austria',
    'Belgium',
    'Canada',
    'Ireland',
    'Japan',
    'Singapore',
    'Hong Kong',
    'South Korea',
    'United Arab Emirates',
]