export const nationalities = [
    { id: 0, value: "Afghan" },
    { id: 1, value: "Albanian" },
    { id: 2, value: "Algerian" },
    { id: 3, value: "American" },
    { id: 4, value: "Andorran" },
    { id: 5, value: "Angolan" },
    { id: 6, value: "Antiguans" },
    { id: 7, value: "Argentinean" },
    { id: 8, value: "Armenian" },
    { id: 9, value: "Australian" },
    { id: 10, value: "Austrian" },
    { id: 11, value: "Azerbaijani" },
    { id: 12, value: "Bahamian" },
    { id: 13, value: "Bahraini" },
    { id: 14, value: "Bangladeshi" },
    { id: 15, value: "Barbadian" },
    { id: 16, value: "Barbudans" },
    { id: 17, value: "Batswana" },
    { id: 18, value: "Belarusian" },
    { id: 19, value: "Belgian" },
    { id: 20, value: "Belizean" },
    { id: 21, value: "Beninese" },
    { id: 22, value: "Bhutanese" },
    { id: 23, value: "Bolivian" },
    { id: 24, value: "Bosnian" },
    { id: 25, value: "Brazilian" },
    { id: 26, value: "British" },
    { id: 27, value: "Bruneian" },
    { id: 28, value: "Bulgarian" },
    { id: 29, value: "Burkinabe" },
    { id: 30, value: "Burmese" },
    { id: 31, value: "Burundian" },
    { id: 32, value: "Cambodian" },
    { id: 33, value: "Cameroonian" },
    { id: 34, value: "Canadian" },
    { id: 35, value: "Cape Verdean" },
    { id: 36, value: "Central African" },
    { id: 37, value: "Chadian" },
    { id: 38, value: "Chilean" },
    { id: 39, value: "Chinese" },
    { id: 40, value: "Colombian" },
    { id: 41, value: "Comoran" },
    { id: 42, value: "Congolese" },
    { id: 43, value: "Costa Rican" },
    { id: 44, value: "Croatian" },
    { id: 45, value: "Cuban" },
    { id: 46, value: "Cypriot" },
    { id: 47, value: "Czech" },
    { id: 48, value: "Danish" },
    { id: 49, value: "Djibouti" },
    { id: 50, value: "Dominican" },
    { id: 51, value: "Dutch" },
    { id: 52, value: "East Timorese" },
    { id: 53, value: "Ecuadorean" },
    { id: 54, value: "Egyptian" },
    { id: 55, value: "Emirian" },
    { id: 56, value: "Equatorial Guinean" },
    { id: 57, value: "Eritrean" },
    { id: 58, value: "Estonian" },
    { id: 59, value: "Ethiopian" },
    { id: 60, value: "Fijian" },
    { id: 61, value: "Filipino" },
    { id: 62, value: "Finnish" },
    { id: 63, value: "French" },
    { id: 64, value: "Gabonese" },
    { id: 65, value: "Gambian" },
    { id: 66, value: "Georgian" },
    { id: 67, value: "German" },
    { id: 68, value: "Ghanaian" },
    { id: 69, value: "Greek" },
    { id: 70, value: "Grenadian" },
    { id: 71, value: "Guatemalan" },
    { id: 72, value: "Guinea-Bissauan" },
    { id: 73, value: "Guinean" },
    { id: 74, value: "Guyanese" },
    { id: 75, value: "Haitian" },
    { id: 76, value: "Herzegovinian" },
    { id: 77, value: "Honduran" },
    { id: 78, value: "Hungarian" },
    { id: 79, value: "Icelander" },
    { id: 80, value: "Indian" },
    { id: 81, value: "Indonesian" },
    { id: 82, value: "Iranian" },
    { id: 83, value: "Iraqi" },
    { id: 84, value: "Irish" },
    { id: 85, value: "Israeli" },
    { id: 86, value: "Italian" },
    { id: 87, value: "Ivorian" },
    { id: 88, value: "Jamaican" },
    { id: 89, value: "Japanese" },
    { id: 90, value: "Jordanian" },
    { id: 91, value: "Kazakhstani" },
    { id: 92, value: "Kenyan" },
    { id: 93, value: "Kittian and Nevisian" },
    { id: 94, value: "Kuwaiti" },
    { id: 95, value: "Kyrgyz" },
    { id: 96, value: "Laotian" },
    { id: 97, value: "Latvian" },
    { id: 98, value: "Lebanese" },
    { id: 99, value: "Liberian" },
    { id: 100, value: "Libyan" },
    { id: 101, value: "Liechtensteiner" },
    { id: 102, value: "Lithuanian" },
    { id: 103, value: "Luxembourger" },
    { id: 104, value: "Macedonian" },
    { id: 105, value: "Malagasy" },
    { id: 106, value: "Malawian" },
    { id: 107, value: "Malaysian" },
    { id: 108, value: "Maldivan" },
    { id: 109, value: "Malian" },
    { id: 110, value: "Maltese" },
    { id: 111, value: "Marshallese" },
    { id: 112, value: "Mauritanian" },
    { id: 113, value: "Mauritian" },
    { id: 114, value: "Mexican" },
    { id: 115, value: "Micronesian" },
    { id: 116, value: "Moldovan" },
    { id: 117, value: "Monacan" },
    { id: 118, value: "Mongolian" },
    { id: 119, value: "Moroccan" },
    { id: 120, value: "Mosotho" },
    { id: 121, value: "Motswana" },
    { id: 122, value: "Mozambican" },
    { id: 123, value: "Namibian" },
    { id: 124, value: "Nauruan" },
    { id: 125, value: "Nepalese" },
    { id: 126, value: "New Zealander" },
    { id: 127, value: "Ni-Vanuatu" },
    { id: 128, value: "Nicaraguan" },
    { id: 129, value: "Nigerien" },
    { id: 130, value: "North Korean" },
    { id: 131, value: "Northern Irish" },
    { id: 132, value: "Norwegian" },
    { id: 133, value: "Omani" },
    { id: 134, value: "Pakistani" },
    { id: 135, value: "Palauan" },
    { id: 136, value: "Panamanian" },
    { id: 137, value: "Papua New Guinean" },
    { id: 138, value: "Paraguayan" },
    { id: 139, value: "Peruvian" },
    { id: 140, value: "Polish" },
    { id: 141, value: "Portuguese" },
    { id: 142, value: "Qatari" },
    { id: 143, value: "Romanian" },
    { id: 144, value: "Russian" },
    { id: 145, value: "Rwandan" },
    { id: 146, value: "Saint Lucian" },
    { id: 147, value: "Salvadoran" },
    { id: 148, value: "Samoan" },
    { id: 149, value: "San Marinese" },
    { id: 150, value: "Sao Tomean" },
    { id: 151, value: "Saudi" },
    { id: 152, value: "Scottish" },
    { id: 153, value: "Senegalese" },
    { id: 154, value: "Serbian" },
    { id: 155, value: "Seychellois" },
    { id: 156, value: "Sierra Leonean" },
    { id: 157, value: "Singaporean" },
    { id: 158, value: "Slovakian" },
    { id: 159, value: "Slovenian" },
    { id: 160, value: "Solomon Islander" },
    { id: 161, value: "Somali" },
    { id: 162, value: "South African" },
    { id: 163, value: "South Korean" },
    { id: 164, value: "Spanish" },
    { id: 165, value: "Sri Lankan" },
    { id: 166, value: "Sudanese" },
    { id: 167, value: "Surinamer" },
    { id: 168, value: "Swazi" },
    { id: 169, value: "Swedish" },
    { id: 170, value: "Swiss" },
    { id: 171, value: "Syrian" },
    { id: 172, value: "Taiwanese" },
    { id: 173, value: "Tajik" },
    { id: 174, value: "Tanzanian" },
    { id: 175, value: "Thai" },
    { id: 176, value: "Togolese" },
    { id: 177, value: "Tongan" },
    { id: 178, value: "Trinidadian or Tobagonian" },
    { id: 179, value: "Tunisian" },
    { id: 180, value: "Turkish" },
    { id: 181, value: "Tuvaluan" },
    { id: 182, value: "Ugandan" },
    { id: 183, value: "Ukrainian" },
    { id: 184, value: "Uruguayan" },
    { id: 185, value: "Uzbekistani" },
    { id: 186, value: "Venezuelan" },
    { id: 187, value: "Vietnamese" },
    { id: 188, value: "Welsh" },
    { id: 189, value: "Yemenite" },
    { id: 190, value: "Zambian" },
    { id: 191, value: "Zimbabwean" }
];
