export interface UserProfile{
  firstName: null,
  lastName:null,
  email: null,
  phoneNumber: null,
  level: null,
  bio: null,
  // discord: null,
  // codeWars: null,
  // github: null,
  // linkedin: null,
  // skills: [],
  // certifications: [],
  // projects: [],
};
